### PR TITLE
Couple of fixes

### PR DESCRIPTION
**Pull request by ceremcem**
# Is breaking

Shouldn't be

### CODE REVIEW

**Comment by ceremcem** [comment]
https://github.com/kouts/ractive-modal/pull/5/commits/eb00caff5b497d3c8b14fdf5364fac5880df5ff1 fixes https://github.com/kouts/ractive-modal/issues/6

**Comment by kouts** [comment]
Fixed with 49faed36932060009ad3c4e08a643b341b6ed18e and fc5dcc43a8982421784d0d43e0e5d9a75d3b646e

**Comment by ceremcem** [comment]
@kouts did you try to make some kind of "cherry pick" by copy&paste of my commits? o_O

**Comment by kouts** [comment]
@ceremcem yes I  haven't included the simple.html demo page and also changed the dev mode to use ```npm run dev``` instead of ```npm run watch```
All your fixes are there, thanks! I'm planning to have more demo pages to demonstrate all features, but
it's better to be in the same format as the main demo page is now.

**Pull request closed without merging**
